@startmindmap
* lystream功能组件

** 顶层前端流
*** 可见光相机流
*** 红外相机流
*** 虚拟相机流

** 前端流和后端流
*** 图像处理流
**** 常用图像处理算子1
**** 常用图像处理算子2
**** ......
*** 算法处理流
**** 常用算法处理算子1
**** 常用算法处理算子2
**** ......
*** Jpeg编码流
*** Video编码流
**** 常用Video处理算子1
**** 常用Video处理算子2
**** ......

@endmindmap