@startuml

component 顶点前端流
顶点前端流-->[业务处理流1]
顶点前端流-->[业务处理流2]
顶点前端流-->other1

card 算子组件1 [
处理算子1
----
处理算子2
----
处理算子3
]

算子组件1-[dotted]->[业务处理流3]
[业务处理流1]-->[业务处理流3]

card 算子组件3 [
处理算子6
]

算子组件3-->[业务处理流2]

[业务处理流1]-->[业务处理流4]
[业务处理流1]-->[业务处理流5]
[业务处理流4]-->other3
[业务处理流5]-->other4

card 算子组件2 [
处理算子4
----
处理算子5
]

算子组件2-[dotted]->[业务处理流6]
[业务处理流2]-->[业务处理流6]
[业务处理流6]-->other5

[业务处理流3]-->[业务处理流7]
[业务处理流7]-->other2

@enduml