@startuml

card 相机参数机制
component 可将光相机数据流
相机参数机制-[dashed]->可将光相机数据流
可将光相机数据流-[dashed]->相机参数机制
可将光相机数据流-->最终业务端点1

card 算子组件1 [
图像处理算子1
----
图像处理算子1
----
图像处理算子1
]

card 算子组件2 [
图像处理算子2
----
图像处理算子2
]

算子组件1-[dotted]->[图像处理流1]
[图像处理流1]-[dotted]->算子组件1
可将光相机数据流-->[图像处理流1]
算子组件2-[dotted]->[图像处理流2]
[图像处理流2]-[dotted]->算子组件2
可将光相机数据流-->[图像处理流2]

card Jpeg编码参数机制
[图像处理流2]-->[Jpeg编码流]
Jpeg编码参数机制-[dashed]->[Jpeg编码流]
[Jpeg编码流]-[dashed]->Jpeg编码参数机制
[Jpeg编码流]-->最终业务端点2
[Jpeg编码流]-->最终业务端点3

[图像处理流1]-->最终业务端点4

@enduml