@startuml

card 相机参数机制
component 可将光相机数据流
相机参数机制-[dashed]->可将光相机数据流
可将光相机数据流-[dashed]->相机参数机制

card 算子组件1 [
DIY算法处理算子1
----
DIY算法处理算子1
----
DIY算法处理算子1
]

card 算子组件2 [
DIY图像处理算子1
----
DIY图像处理算子1
]

算子组件1-[dotted]->[算法处理流1]
[算法处理流1]-[dotted]->算子组件1
可将光相机数据流-->[算法处理流1]
可将光相机数据流-->[DIY算法处理流2]
[算法处理流1]-->other1
[算法处理流1]-->other2
[DIY算法处理流2]-->other4

可将光相机数据流-->[图像处理流1]
算子组件2-[dotted]->[图像处理流1]
[图像处理流1]-[dotted]->算子组件2
[图像处理流1]-->other3


@enduml