@startuml

frame 可见光相机1数据链路 {
card 相机参数1
component 可将光相机1数据流
相机参数1-[dashed]->可将光相机1数据流
可将光相机1数据流-[dashed]->相机参数1

可将光相机1数据流-->[算法处理流1]
可将光相机1数据流-->[图像处理流1]
[算法处理流1]-->other1
[图像处理流1]-->other2
}

frame 可见光相机2数据链路 {
card 相机参数2
component 可将光相机2数据流
相机参数2-[dashed]->可将光相机2数据流
可将光相机2数据流-[dashed]->相机参数2
可将光相机2数据流-->[Jpeg编码流1]
可将光相机2数据流-->[Video编码流1]
[Jpeg编码流1]-->other3
[Video编码流1]-->other4
}

frame 红外相机数据链路 {
component 红外相机数据流
红外相机数据流-->[Jpeg编码流2]
红外相机数据流-->[图像处理流2]
[Jpeg编码流2]-->other5
[图像处理流2]-->other6
}

frame 虚拟相机数据链路 {
component 虚拟相机数据流
虚拟相机数据流-->[Video编码流2]
虚拟相机数据流-->[图像处理流3]
[Video编码流2]-->other7
[图像处理流3]-->other8
}

@enduml