@startmindmap
* DaHeng和HIK
** 支持任意款型号相机
** 目前使用均为彩色USB相机
** 图像统一获取Bayer图像
*** 第一路Bayer图像转码：Bayer->RGB24->YUV420P

**** Jpeg编码
***** 不抽帧，帧率和相机帧率一样
***** 编码后，封装数据结构
****** TCP传送上位机

**** Video编码（主码流）
***** 抽帧，帧率由配置参数决定
***** 编码类型由配置参数决定
***** 编码后，尾部添加DIY SEI帧（带有是时间戳信息）
****** 写到对应的RTSP服务缓冲中，发送

**** 可将光算法处理
***** 每帧执行
****** 受电弓震动
****** 受电弓动态几何参数
****** 燃弧
****** 定位点识别
***** 间隔执行（10S一次）
****** 异物
****** 羊角缺失
****** 受电弓磨耗
****** 受电弓角度

***** 算法结果数据融合
****** TCP端口发送


*** 第二路Bayer图像转码：Bayer->RGB24->Resize->YUV420P（缩放版）
**** Video编码（子码流）
***** 抽帧，帧率由配置参数决定
***** 编码类型由配置参数决定
***** 编码后，尾部添加DIY SEI帧（带有是时间戳信息）
****** 写到对应的RTSP服务缓冲中，发送

@endmindmap