@startuml
card 相机参数机制
component 可将光相机数据流
相机参数机制-[dashed]->可将光相机数据流
可将光相机数据流-[dashed]->相机参数机制
可将光相机数据流 --> 统计相机FPS


card 算子组件1 [
Bayer2YUV420算子1
----
Bayer2YUV420算子1
]
card 算子组件2 [
Bayer2YUV420withResize算子1
----
Bayer2YUV420withResize算子2
]
card 算子组件3 [
Gray2YUV420算子1
----
Gray2YUV420算子1
]
card 算子组件4 [
Gray2YUV420withResize算子1
----
Gray2YUV420withResize算子2
]

算子组件1-[dotted]->[图像处理流1]
[图像处理流1]-[dotted]->算子组件1

算子组件2-[dotted]->[图像处理流2]
[图像处理流2]-[dotted]->算子组件2

算子组件3-[dotted]->[图像处理流3]
[图像处理流3]-[dotted]->算子组件3

算子组件4-[dotted]->[图像处理流4]
[图像处理流4]-[dotted]->算子组件4

可将光相机数据流 --> [图像处理流1]
可将光相机数据流 --> [图像处理流2]
可将光相机数据流 --> [图像处理流3]
可将光相机数据流 --> [图像处理流4]

[图像处理流1] --> [Jpeg编码流]
[Jpeg编码流] --> 封装数据和TCP传输
[图像处理流1] --> [Video编码流1]
[Video编码流1] --> 尾部加入SEI帧和RTSP传送主码流

[图像处理流1] --> [可见光算法流]
[可见光算法流] --> TCP1端口发送
[可见光算法流] --> TCP2端口发送

[图像处理流2] --> [Video编码流2]
[Video编码流2] --> 尾部加入SEI帧和RTSP传送子码流
@enduml