@startuml

card Jpeg编码参数

package "红外相机" {
    [红外相机数据流]-->[Jpeg编码流3]
    [Jpeg编码流3]-->业务端点10
    [Jpeg编码流3]-->业务端点11

    [Jpeg编码流3]-[dotted]->Jpeg编码参数
    Jpeg编码参数-[dotted]->[Jpeg编码流3]

    [红外相机数据流]->[图像处理流4]
    card 算子组件5 [
        DIY图像处理算子4
        ----
        DIY图像处理算子4
    ]
    算子组件5-[dashed]->[图像处理流4]
    [图像处理流4]-[dashed]->算子组件5
    [图像处理流4]->[算法处理流2]

    card 算子组件6 [
        DIY算法处理算子2
        ----
        DIY算法处理算子2
    ]
    算子组件6-[dashed]->[算法处理流2]
    [算法处理流2]-[dashed]->算子组件6
    [算法处理流2]-->业务端点12

}
@enduml